import request from './request'

export const login = (data) => request.post('/auth/login', data)
export const logout = () => request.post('/auth/logout')
export const getUserInfo = () => request.get('/auth/info')

export const getCustomerList = (params) => request.get('/customer/list', { params })
export const getCustomer = (id) => request.get(`/customer/${id}`)
export const addCustomer = (data) => request.post('/customer', data)
export const updateCustomer = (id, data) => request.put(`/customer/${id}`, data)
export const deleteCustomer = (id) => request.delete(`/customer/${id}`)
export const getCustomerOrders = (id) => request.get(`/customer/${id}/orders`)

export const getOrderList = (params) => request.get('/order/list', { params })
export const getOrder = (id) => request.get(`/order/${id}`)
export const addOrder = (data) => request.post('/order', data)
export const updateOrder = (id, data) => request.put(`/order/${id}`, data)
export const deleteOrder = (id) => request.delete(`/order/${id}`)
export const updateOrderStatus = (id, status) => request.put(`/order/${id}/status`, { status })
export const getOrderStatistics = (params) => request.get('/order/statistics', { params })

export const getMaterialList = (params) => request.get('/material/list', { params })
export const getMaterial = (id) => request.get(`/material/${id}`)
export const addMaterial = (data) => request.post('/material', data)
export const updateMaterial = (id, data) => request.put(`/material/${id}`, data)
export const deleteMaterial = (id) => request.delete(`/material/${id}`)
export const addMaterialPurchase = (data) => request.post('/material/purchase', data)
export const getPurchaseList = (params) => request.get('/material/purchase/list', { params })
export const addMaterialConsumption = (data) => request.post('/material/consumption', data)
export const getConsumptionList = (params) => request.get('/material/consumption/list', { params })
export const getStockAlert = () => request.get('/material/stock/alert')

export const addLabor = (data) => request.post('/labor', data)
export const getLaborList = (params) => request.get('/labor/list', { params })
export const updateLabor = (id, data) => request.put(`/labor/${id}`, data)
export const deleteLabor = (id) => request.delete(`/labor/${id}`)

export const getQuoteTemplateList = () => request.get('/quote/template/list')
export const addQuoteTemplate = (data) => request.post('/quote/template', data)
export const getOrderQuote = (orderId) => request.get(`/quote/order/${orderId}`)
export const saveOrderQuote = (data) => request.post('/quote/order', data)
export const exportQuote = (orderId) => request.get(`/quote/export/${orderId}`, { responseType: 'blob' })

export const addPayment = (data) => request.post('/payment', data)
export const getPaymentList = (params) => request.get('/payment/list', { params })
export const updatePayment = (id, data) => request.put(`/payment/${id}`, data)
export const deletePayment = (id) => request.delete(`/payment/${id}`)
export const getOrderPayments = (orderId) => request.get(`/payment/order/${orderId}`)

export const getMonthProfit = (params) => request.get('/statistics/profit/month', { params })
export const getYearProfit = (params) => request.get('/statistics/profit/year', { params })
export const getCostAnalysis = (params) => request.get('/statistics/cost/analysis', { params })
export const getOrderStatusStat = () => request.get('/statistics/order/status')
export const getCustomerValue = () => request.get('/statistics/customer/value')
export const getDashboard = () => request.get('/statistics/dashboard')

export const getSystemConfig = () => request.get('/system/config')
export const updateSystemConfig = (data) => request.put('/system/config', data)
export const getOperationLog = (params) => request.get('/system/log', { params })
export const backupData = () => request.post('/system/backup')
export const restoreData = (data) => request.post('/system/restore', data)
